### ISSUE TITLE
ToDo List 

### ISSUE THREAD

**Issue by syedjafer** [cts-student-club/Patient-Care-App#4]
:sunglasses:

- [ ] Login Api (FireBase Integration)
###  Pages
- [ ] Home Page { Details About Next Dosage }
- [ ] Profile { Normal Bio , Emergency Contact Numbers , Medical History}
- [ ] Medicine Purchase { User Should Upload details of Medicines Purchased with their Numbers . }
- [ ] Push Notifications for Medicine Renewal . 
## If Possible . 
- [ ] Fixing appointments with Hospitals for Checkup . 
- [ ] while changing to other phones , backup of data should be taken .

**Comment by garrykevin-ep** [comment]
We wont need backend ,we can  store data in Client itself @syedjafer
